### install

- name: install zsh
  apt: name={{ item }} state=present
  with_items:
    - zsh

### change default shell

- name: shell | change default shell to zsh for user vagrant
  command: /usr/bin/chsh -s /usr/bin/zsh vagrant

- name: shell | change default shell to zsh for user root
  command: /usr/bin/chsh -s /usr/bin/zsh root

### oh my zsh

- stat: path=/tmp/ohmyzsh-installer
  register: ohmyzsh_installer

- name: download ohmyzsh installer
  get_url:
    url=https://raw.github.com/robbyrussell/oh-my-zsh/master/tools/install.sh
    dest=/tmp/ohmyzsh-installer
    owner=vagrant
    group=vagrant
    mode=0777
  when: zsh.ohmyzsh.enable == true and ohmyzsh_installer.stat.exists == false

- stat: path=/home/vagrant/.oh-my-zsh
  register: vagrant_ohmyzsh_installed

- name: install ohmyzsh for user vagrant
  command: '/bin/sh /tmp/ohmyzsh-installer'
  become_user: vagrant
  when: zsh.ohmyzsh.enable == true and vagrant_ohmyzsh_installed.stat.exists == false

- stat: path=/root/.oh-my-zsh
  register: root_ohmyzsh_installed

- name: install ohmyzsh for user root
  command: '/bin/sh /tmp/ohmyzsh-installer'
  when: zsh.ohmyzsh.enable == true and root_ohmyzsh_installed.stat.exists == false

### config

- name: copy .zshrc for user vagrant
  template:
    src=zshrc.j2
    dest=/home/vagrant/.zshrc
    owner=vagrant
    group=vagrant

- name: copy .zshrc for user root
  template:
    src=zshrc.j2
    dest=/root/.zshrc
    owner=root
    group=root
