### change default shell

- name: shell | change default shell to bash for user vagrant
  command: /usr/bin/chsh -s /bin/bash vagrant

- name: shell | change default shell to bash for user root
  command: /usr/bin/chsh -s /bin/bash root

### config

- name: copy .bashrc for user vagrant
  template:
    src=bashrc.j2
    dest=/home/vagrant/.bashrc
    owner=vagrant
    group=vagrant

- name: copy .bashrc for user root
  template:
    src=bashrc.j2
    dest=/root/.bashrc
    owner=root
    group=root
