---
- hosts: all
  sudo: true
  roles:
    - general
    - { role: elasticsearch, when: role.elasticsearch }
    - { role: freetds, when: role.freetds }
    - git
    - { role: hhvm, when: phpversion == 'hhvm' }
    - { role: mariadb, when: role.mariadb }
    - { role: memcached, when: role.memcached }
    - { role: mongodb, when: role.mongodb }
    - { role: nginx-application-bolt2, when: application == 'bolt2' }
    - { role: nginx-application-contao3, when: application == 'contao3' }
    - { role: nginx-application-drupal7, when: application == 'drupal7' }
    - { role: nginx-application-lavarel5, when: application == 'lavarel5' }
    - { role: nginx-application-symfony2, when: application == 'symfony2' }
    - { role: nginx-application-wordpress4, when: application == 'wordpress4' }
    - nginx
    - { role: nodejs, when: role.nodejs }
    - { role: php56-original, when: phpversion == '5.6-original' }
    - { role: php70, when: phpversion == 7.0 }
    - php-tools
    - { role: php-application-drupal7, when: application == 'drupal7' }
    - { role: php-application-symfony2, when: application == 'symfony2' }
    - { role: php-application-wordpress4, when: application == 'wordpress4' }
    - { role: postgresql, when: role.postgresql }
    - { role: redis, when: role.redis }
    - { role: ruby, when: role.ruby }
    - cleanup
