---
- hosts: all
  sudo: true
  roles:
    - general
    - { role: bash, when: general.config.shell == 'bash' }
    - { role: elasticsearch, when: role.elasticsearch }
    - { role: freetds, when: role.freetds }
    - git
    - { role: hhvm, when: phpversion == 'hhvm' }
    - { role: mariadb, when: role.mariadb }
    - { role: memcached, when: role.memcached }
    - { role: mongodb, when: role.mongodb }
    - { role: nginx-application-bolt2, when: "'bolt2' in applications" }
    - { role: nginx-application-contao3, when: "'contao3' in applications" }
    - { role: nginx-application-drupal7, when: "'drupal7' in applications" }
    - { role: nginx-application-drupal8, when: "'drupal8' in applications" }
    - { role: nginx-application-lavarel5, when: "'lavarel5' in applications" }
    - { role: nginx-application-magento1, when: "'magento1' in applications" }
    - { role: nginx-application-symfony1, when: "'symfony1' in applications" }
    - { role: nginx-application-symfony2, when: "'symfony2' in applications" }
    - { role: nginx-application-symfony3, when: "'symfony3' in applications" }
    - { role: nginx-application-wordpress4, when: "'wordpress4' in applications" }
    - { role: nginx-application-shopware, when: "'shopware' in applications" }
    - nginx
    - { role: nodejs, when: role.nodejs }
    - { role: php56-original, when: phpversion == '5.6-original' }
    - { role: php70, when: phpversion == 7.0 }
    - php-tools
    - php-application
    - { role: php-application-drupal7, when: "'drupal7' in applications" }
    - { role: php-application-drupal8, when: "'drupal8' in applications" }
    - { role: php-application-symfony2, when: "'symfony2' in applications" }
    - { role: php-application-symfony3, when: "'symfony3' in applications" }
    - { role: php-application-wordpress4, when: "'wordpress4' in applications" }
    - { role: postgresql, when: role.postgresql }
    - { role: redis, when: role.redis }
    - { role: ruby, when: role.ruby }
    - { role: zsh, when: general.config.shell == 'zsh' }
    - cleanup
